x-veld:
  executable:
    about:
      description: "example veld for testing and showcasing"
      topics: "ETL"
    input:
      type: "files"
      format: "json"
      content: "dummy data"
      # The folders inside an executable could be anything you want. But is is recommended to stick
      # to /veld/input, etc. for consistency
      path: /veld/input/data.json
    output:
      type: "files"
      format: "xml"
      content: "dummy data"
      # Recommended path for anything output related is /veld/output/
      path: /veld/output/data.xml

services:
  veld:
    build: .
    volumes:
      - /home/steff-vm/exp/prefect/exp_1/prefect_server/veld_chain_ex2_json_to_xml/veld_executable_ex2_json_to_xml/convert.py:/veld/executable/convert.py
    command: python /veld/executable/convert.py

