services:
  prefect_server:
    build: 
      context: .
      dockerfile: prefect_server.dockerfile
    volumes:
      - ./prefect_server/:/home/docker_user/
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    command: prefect server start
    networks:
      - prefect_network
    depends_on:
      postgres_db:
        condition: service_started 

  postgres_db:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourTopSecretPassword
      POSTGRES_DB: prefect
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
    networks:
      - prefect_network

#    image: docker run -d --name prefect-postgres -v prefectdb:/var/lib/postgresql/data -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=yourTopSecretPassword -e POSTGRES_DB=prefect postgres:latest


  prefect_client:
    build: 
      context: .
      dockerfile: prefect_client.dockerfile
    volumes:
      - ./prefect_client/:/home/docker_user
    networks:
      - prefect_network

networks:
  prefect_network:

