services:
  prefect_server:
    build: 
      context: .
      dockerfile: prefect_server.dockerfile
    volumes:
      - ./prefect_server/:/home/docker_user/
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    command: prefect server start
    networks:
      - prefect_network

  prefect_client:
    build: 
      context: .
      dockerfile: prefect_client.dockerfile
    volumes:
      - ./prefect_client/:/home/docker_user
    networks:
      - prefect_network

networks:
  prefect_network:

