services:
  orion:
    image: prefecthq/prefect:2.10-python3.9
#    restart: always
    volumes:
      - ./prefect_volume:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
