services:
  prefect_server:
    build: 
      context: .
      dockerfile: prefect_server.dockerfile
    volumes:
      - ./:/home/docker_user
    #entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    command: prefect server start

  prefect_client:
    build: 
      context: .
      dockerfile: prefect_server.dockerfile
    volumes:
      - ./:/home/docker_user


