services:
  prefect:
    build: .
    volumes:
      - ./:/home/docker_user
    #entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    command: prefect server start

