x-veld:
  executable:
    about:
      description: "example veld for testing and showcasing"
      topics: "data validation"
    input:
      # executables can take several inputs / outputs. If that is the case, define them as a list
      -
        type: "files"
        format: "xml"
        content: "dummy data"
        path: /veld/input/data.xml
      -
        type: "files"
        format: "xsd"
        content: "dummy data"
        path: /veld/input/schema.xsd
        optional: true
    output:
      type: "files"
      format: "txt"
      content: "dummy data"
      path: /veld/output/result.txt

services:
  veld:
    build: .
    volumes:
      - /home/steff-vm/exp/prefect/exp_1/prefect_server/veld_chain_ex5_fetch_convert_validate_load/veld_executable_ex3_validate_xml/validate.sh:/veld/executable/validate.sh
    command: bash /veld/executable/validate.sh


